### ISSUE TITLE
mfw setup Windows 10 - error symlink

### ISSUE THREAD

**Issue by Softovick** [microservice-framework/api-todo-example-2#1]
I run mfw setup with node 8 and node 10. Result:
---
NODEJS 8.15 NPM 6.4.1
---
```
 mfw setup
        -       downloading microservice-router
        -       downloading example-todo
        -       downloading microservice-auth
        -       downloading microservice-users-login
        -       downloading microservice-users
        -       copiyng microservice-auth to C:\dev\njs\mfw\api-todo-example-2/services/microservice-auth
        -       updating dependencies for microservice-auth
        -       copiyng microservice-router to C:\dev\njs\mfw\api-todo-example-2/services/microservice-router
        -       updating dependencies for microservice-router
fs.js:1014
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'C:\dev\njs\mfw\api-todo-example-2\configs\microservice-auth.env' -> 'C:\dev\njs\mfw\api-todo-example-2\services\microservice-auth\.env'
    at Object.fs.symlinkSync (fs.js:1014:18)
    at Object.createSymlinkSync (C:\ProgramData\nvm\v8.15.0\node_modules\@microservice-framework\mfw-cli\node_modules\fs-extra\lib\ensure\symlink.js:53:25)
    at C:\ProgramData\nvm\v8.15.0\node_modules\@microservice-framework\mfw-cli\includes\MFWCliClass.js:952:17
    at C:\ProgramData\nvm\v8.15.0\node_modules\@microservice-framework\mfw-cli\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:152:21)

```
---
NODE.JS 10.15 NPM 6.4.1
---
```
mfw setup
        -       downloading microservice-router
        -       downloading example-todo
        -       downloading microservice-auth
        -       downloading microservice-users
        -       downloading microservice-users-login
        -       copiyng microservice-auth to C:\dev\njs\mfw\api-todo-example-2/services/microservice-auth
        -       updating dependencies for microservice-auth
        -       copiyng microservice-router to C:\dev\njs\mfw\api-todo-example-2/services/microservice-router
        -       updating dependencies for microservice-router
        -       copiyng microservice-users-login to C:\dev\njs\mfw\api-todo-example-2/services/microservice-users-login
        -       updating dependencies for microservice-users-login
        -       copiyng microservice-users to C:\dev\njs\mfw\api-todo-example-2/services/microservice-users
        -       updating dependencies for microservice-users
        -       copiyng example-todo to C:\dev\njs\mfw\api-todo-example-2/services/example-todo
        -       updating dependencies for example-todo
fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'C:\dev\njs\mfw\api-todo-example-2/configs/microservice-users.env' -> 'C:\dev\njs\mfw\api-todo-example-2/services/microservice-users/.env'
    at Object.symlinkSync (fs.js:905:3)
    at Object.createSymlinkSync (C:\ProgramData\nvm\v10.15.0\node_modules\@microservice-framework\mfw-cli\node_modules\fs-extra\lib\ensure\symlink.js:53:25)
    at C:\ProgramData\nvm\v10.15.0\node_modules\@microservice-framework\mfw-cli\includes\MFWCliClass.js:952:17
    at C:\ProgramData\nvm\v10.15.0\node_modules\@microservice-framework\mfw-cli\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:154:21)
```

**Comment by Softovick** [comment]
only for Linux Windows Subsystem work (ubuntu 18.04).... but it is uncomfortable
